woowa-techcamp-2021/cashbook-03

client/package-lock.json
client/package.json
client/src/App.ts
client/src/Router.ts
client/src/components/Header.ts
client/src/containers/HeaderContainer.ts
client/src/index.html
client/src/pages/Calendar.ts
client/src/pages/Error.ts
client/src/pages/Main.ts
client/src/pages/Statistics.ts
client/src/store.ts
client/src/utils/View/index.ts
client/src/utils/api/client.ts

- 전역상태관리 store
- observer패턴, 클로저 사용
- 라우터 Router
- 히스토리 api이용해서 페이지 이동
- 없는 페이지는 404 페이지로 이동
- 페이지
- 페이지에서는 컨테이너의 내용을 받아와서 렌더링
- 컨테이너
- 컨테이너는 controller 역할.
- 전역 상태를 받아오는 역할
- 이벤트 위임으로 컴포넌트 제어
- state가 바뀜에 따라 컴포넌트 rerender
- 컴포넌트
- 오로지 View의 역할
- 유틸
- api : axios에 옵션을 적용하고 불러와서 사용
- View : 컨테이너의 부모역할. 공통되는 역할이 있어 만들어 놓음. 추후 수정 가능
resolve #10

[#10] feat: 프론트 기본 프레임 완성

---

server/src/controllers/account.ts
server/src/types/express.d.ts
server/tsconfig.json

[#35] bug: req.user 버그 수정

---

client/.babelrc
client/package-lock.json
client/package.json
client/src/App.ts
client/src/components/Header/Header.ts
client/src/components/SignMain/SignMain.scss
client/src/components/SignMain/SignMain.ts
client/src/containers/HeaderContainer.ts
client/src/containers/SignContainer.ts
client/src/utils/api/auth.ts
client/webpack.config.js
server/.env.sample
server/package-lock.json
server/package.json
server/src/app.ts
server/src/config/index.ts
server/src/controllers/auth.ts
server/src/controllers/user.ts
server/src/passport/github.ts
server/src/passport/local.ts
server/src/repository/user.ts
server/src/service/payment.ts

[#38] 로그인 서버와 프론트 병합

---

client/src/components/MainTab/MainTab.scss
client/src/components/MainTab/MainTab.ts
client/src/pages/Main.ts
client/src/public/styles/index.scss
client/src/public/styles/reset.scss

말그대로 스타일링입니다. 기능구현하다보니 자잘한 부분이 조금 바뀌긴 하고 있네요. 아마 크게는 바뀌지 않을 것 같습니다.
특별한 건 없는것같네요
#13

[#13] feat: 메인 탭 스타일링

---

server/src/app.ts
server/src/controllers/payment.ts
server/src/controllers/user.ts
server/src/passport/github.ts
server/src/repository/payment.ts
server/src/repository/user.ts
server/src/service/payment.ts
server/src/service/user.ts

- App.ts 간단한 리팩토링 (path 변수화)
- 기존 GET /payment 수정
- POST, DELETE 추가
- #8 
- #42 (추가)
- ~~회원가입될 때 기본 결제수단 추가는 브랜치 머지되면 작업 시작하겠습니다. 관련 이슈는 따로 추가해놓을게요~~
- #42 완료. 현재 PR 머지되면 따로 올리겠습니다.

[#8] 결제수단 API, [#42] 회원가입시 기본 결제수단 등록

---

server/src/controllers/account.ts
server/src/repository/account.ts
server/src/service/account.ts

- 기존 GET 논의된 내용 바탕으로 수정 (query parameter로 조건 받도록)
- POST 메시지 수정
- DELETE 추가
- #9 
- #7 
- timestamp 형식 ISOString으로 받는 것으로 논의됨
- GET 요청시 year는 필수 query parameter

[#9] 지출 내역 API 완료

---

server/package.json
server/src/controllers/account.ts
server/src/controllers/payment.ts
server/src/model/account.ts
server/src/model/category.ts
server/src/model/payment.ts
server/src/model/user.ts
server/src/passport/github.ts
server/src/passport/index.ts
server/src/repository/account.ts
server/src/repository/payment.ts
server/src/service/payment.ts
server/src/service/user.ts
server/src/types/express.d.ts
server/tsconfig.json

- req.user 문제 해결 (passport 관련된 부분까지는 해결 안됨)
- 모델들 타입 선언, 관련 코드 리팩토링 (any로 처리했던 부분들 변경)
- #44 
- @HanCheo 김한철님 도움을 많이 받음. 감사합니다.

[#44] User 및 모델들 타입 선언, 관련 코드 리팩토링

---

client/src/components/Calendar/Calendar.scss
client/src/components/Calendar/Calendar.ts
client/src/components/SignHeader/SignHeader.ts
client/src/components/SignMain/SignMain.ts
client/src/containers/CalendarContainer.ts
client/src/containers/SignContainer.ts
client/src/pages/Calendar.ts
client/src/pages/Login.ts
client/src/public/styles/index.scss
client/src/public/styles/mixins.scss

- 저번에 슬랙에서 이야기한 로그인 페이지 div 하나 더 들어가는거 수정한 커밋도 여기에 포함되었습니다
- mixin에 elevation (그림자 줘서 띄우는거) 추가했습니다. 충돌 생기거나 중복될까봐 미리 말씀드립니다.
- 데이터를 가져와서 어떻게 처리할지가 아직 미정이라 컴포넌트 잘게 나누거나 하는 것들은 기능 만들 때 추가해야 할 것 같아요.
#14

[#14] 달력 탭 스타일링

---

client/src/App.ts
client/src/components/MainTab/MainTab.scss
client/src/components/MainTab/MainTab.ts
client/src/components/SignMain/SignMain.scss
client/src/components/SignMain/SignMain.ts
client/src/containers/MainTabContainer.ts
client/src/pages/Main.ts
client/src/store.ts
client/src/utils/api/account.ts
client/src/utils/api/category.ts
client/src/utils/api/payment.ts

- 문제가 계속생겨서 pr을 너무 늦게올렸네요... 죄송합니다
- 방금 오류를 발견했는데 한글 입력시에 ㄴㅐㄱㅏ  이런식으로 입력되네요... 수정해서 올릴게요
- input date부분을 제외하고는 전부 state가 동적으로 바뀝니다.
- input text change이벤트를 없애고 input으로 했는데 그 버튼 바꾸는게 onchange에서는 안되서 input으로 했어요
- 근데 그러면서 문제가 발생했네요...
#18

[#18] feat: 메인탭 기능추가

---

client/src/App.ts
client/src/containers/MainTabContainer.ts
client/src/store/account.ts
client/src/store/index.ts
client/src/utils/api/account.ts

간단히 리팩토링 했습니다. 오류가 딱히 아직은 안보이네요
#51

[#51] 프론트 구조 통합 후 리팩토링

---

client/src/utils/View/index.ts

- 기존 방식(모든 attribute를 없앴다가 추가)은 비효율적이고 나중에 버그를 발생시킬 수도 있을 것 같아서 수정
- 커밋 메시지에 로직 적어놓음
- 잘 준비하면서 곰곰히 생각해보다가 아무래도 기존 방식은 좀 아닌 거 같아서 수정하고 PR 올립니다.

attribute 업데이트 방식 리팩토링

---

client/src/App.ts
client/src/containers/MainTabContainer.ts
client/src/store/account.ts
client/src/utils/Observable/index.ts
client/src/utils/api/account.ts

[#56] account 공통부분

---

client/src/components/Account/Account.scss
client/src/components/Account/Account.ts
client/src/pages/Main.ts
client/src/public/styles/index.scss

[#58] wip: 메인 account ui

---

client/src/App.ts
client/src/components/Account/Account.scss
client/src/components/Account/Account.ts
client/src/components/Account/AccountHeader.ts
client/src/components/Account/AccountItem.ts
client/src/components/MainTab/MainTab.ts
client/src/containers/AccountContainer.ts
client/src/containers/MainTabContainer.ts
client/src/pages/Main.ts
client/src/public/styles/index.scss
client/src/utils/chore.ts
server/src/repository/account.ts

[#19] 메인화면 accounnt 기능 완성

---

client/src/App.ts
client/src/Router.ts
client/src/components/Calendar/Calendar.ts
client/src/components/Calendar/CalendarContent/CalendarContent.ts
client/src/components/Calendar/CalendarContent/sub-components/index.ts
client/src/components/Calendar/helpers/index.ts
client/src/containers/CalendarContainer.ts
client/src/utils/View/index.ts
server/src/model/index.ts

- 일별 지출, 수입, 계
- 월 지출, 수입, 계
- 탭 전환시 observer 구독 취소되는 부분 임시 수정
#20

[#20] 달력 탭 기능

---

client/src/containers/SignContainer.ts
client/src/utils/api/client.ts

[#63] bug: front에서 서버로 갈때 url 수정 (http)

---

client/src/components/MainChart/CategoryList.ts
client/src/components/MainChart/MainChart.scss
client/src/components/MainChart/MainChart.ts
client/src/containers/DonutContainer.ts
client/src/containers/MainChartContainer.ts
client/src/pages/Statistics.ts
client/src/public/styles/index.scss

[#21] 통계 탭 도넛그래프 오른쪽 부분 완성

---

client/src/components/Calendar/CalendarContent/CalendarContent.ts

[#20] 달력 탭: 오늘 날짜 다르게 표시하기

---

client/src/components/MainChart/Donut.ts
client/src/components/MainChart/MainChart.scss
client/src/components/MainChart/MainChart.ts
client/src/containers/MainChartContainer.ts
client/src/pages/Statistics.ts

- 도넛 차트 구현
- 애니메이션 적용
- but 코드가 이상해짐....
#21

[#21] 도넛 차트 완성

---

client/.babelrc
client/package-lock.json
client/package.json
client/src/components/LineChart/LineChart.scss
client/src/components/LineChart/LineChart.ts
client/src/components/MainChart/CategoryList.ts
client/src/components/MainChart/MainChart.scss
client/src/components/MainChart/MainChart.ts
client/src/components/StatAccountList/StatAccountList.scss
client/src/components/StatAccountList/StatAccountList.ts
client/src/containers/MainChartContainer.ts
client/src/pages/Statistics.ts
client/src/public/styles/index.scss
client/src/store/category.ts
client/src/utils/api/account.ts
server/package-lock.json
server/src/controllers/account.ts
server/src/repository/account.ts
server/src/service/account.ts

- 차트 각자 만든 것 머지, 불러오는 로직 리팩토링
- 꺾은선 그래프 하단 내역 랜더링
- 기타 자잘한 스타일링, 버그 수정
- 게더에서 설명한 바벨 설정 변경
- #22

[#22] 통계탭 기능 완성

---

client/src/App.ts
client/src/components/Header/Header.ts
client/src/index.html
client/src/public/styles/font.scss
client/src/public/styles/index.scss
client/src/public/styles/loader.scss
client/src/utils/api/client.ts
client/src/utils/loader/index.ts

- 서버 요청 때 로딩 중임을 표시
- 추가 액션 방지
- #75

서버 요청 시 로딩 UI

---

client/src/components/Account/Account.scss
client/src/components/Account/Account.ts
client/src/components/Header/Header.ts
client/src/components/MainChart/MainChart.scss
client/src/components/MainChart/MainChart.ts
client/src/components/MainTab/MainTab.scss
client/src/components/MainTab/MainTab.ts
client/src/containers/MainTabContainer.ts

- 빈 데이터 ui 처리
- 애니메이션 적용
- 메인탭 로그인 안됬을 때 클릭 시 모달창 띄우고 settimeout으로 리다이렉트
#73

[#73] Fe/error UI 적용

---

client/src/components/Account/Account.ts
client/src/components/MainChart/MainChart.ts
client/src/containers/AccountContainer.ts
client/src/containers/MainChartContainer.ts

- 텍스트가 나오지 않아야되는데 나오는 경우 오류 수정
#79

[#79] Fe/bug 

---

client/src/containers/MainChartContainer.ts

[#79] bug: 진짜 마지막 버그 수정
